// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace GSN.Skill.Games.Common.Client.DebugMenu
{
    public abstract class CloseableDebugMenu : BaseDebugMenu
    {
#if DEBUG
		private ConfirmMode confirmMode = ConfirmMode.None;
		Vector2 scrollPos;

		enum ConfirmMode
		{
			None,
			Restart,
			Reset,
		}

        /// Override this function in your debnug menu to get elements to draw.
        public override void OnWindow(int windowID)
        {   
            //GUI.Box(new Rect(2,20,windowRect.width-4,windowRect.height-2-20), GUIContent.none); // hack to make window more opaque
            
            if(GUI.Button(new Rect(windowRect.width - 30, 0, 30, 20), "X")) {
                gameObject.SetActive(!gameObject.activeSelf);
            }
            
            if(confirmMode != ConfirmMode.None) {
                if(GUI.Button(new Rect(0, 0, 60, 20), "Cancel")) {
                    confirmMode = ConfirmMode.None;
                }
            }

            scrollPos = GUILayout.BeginScrollView(scrollPos);
 
            GUILayout.EndScrollView();
            
            GUI.DragWindow(new Rect(0, 0, windowRect.width, windowRect.height));
        }
#else
    public override void OnWindow(int windowID) {}
#endif

    }
}

