// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace GSN.Skill.Games.Common.Client.DebugMenu
{
	internal class SpeedDebugMenu : CloseableDebugMenu
    {
#if DEBUG
		public override void OnWindow(int windowID)
		{			
			GUI.color = Color.white;
			
			GUILayout.BeginHorizontal ();
			GUILayout.Label ("Time Scale: " + Time.timeScale);
			if (GUILayout.Button (TimeScale.instance.Paused ? "Unpause" : "Pause")) {
				TimeScale.instance.TogglePause ();
			}
			GUILayout.EndHorizontal ();
			GUILayout.BeginHorizontal ();
			
			if (GUILayout.Button ("Reset")) {
				TimeScale.instance.Reset ();
			}
			
			GUILayout.EndHorizontal ();
			GUILayout.BeginHorizontal ();
			
			if (GUILayout.Button ("Up")) {
				TimeScale.instance.Modify (0.5f);
			}
			
			if (GUILayout.Button ("Down")) {
				TimeScale.instance.Modify (-0.5f);
			}
			GUILayout.EndHorizontal ();

			base.OnWindow (windowID);
		}
#endif
    }
}

