// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEditor;
using GSN.Skill.Games.Tripeaks;

[InitializeOnLoad]
class LoadStringTable
{
    static LoadStringTable ()
    {
        new TriPeaksStringTable ();
    }
    //Todo: Need to be able to refresh from back end data.
    
}
