// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace GSN.Skill.Games.Common.Client.DebugMenu 
{
    public class DebugMenuStartButton : MonoBehaviour
    {
        public void StartGame()
        {
            GameObject debugMenu = GameObject.Find("DebugMenu"); 
            if (debugMenu != null) 
            {
				ArenaDebugMenu go = debugMenu.GetComponent<ArenaDebugMenu>();
                if (go != null)
                {
					go.StartGame();
                }
                else
                {
                    Debug.LogWarning("Found a debug menu component");   
                }
            }
        }
    }
}

