// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
using GSN.Skill.Games.Common.Client;

namespace GSN.Skill.Games.Tripeaks
{
    public class TriPeaksStringTable 
    {
		public TriPeaksStringTable()
        {
			StringTable.instance.table = new Dictionary<string, string> () 
	        {
	            {"START_BUTTON",        "START NOW"},
				{"STARTS_IN",			"STARTS IN"},
				{"GENERIC_TIP_1",       "When choosing between two cards, pick the one that uncovers the most cards."},
				{"GENERIC_TIP_2",       "Keep the streak alive, it's a great way to earn bonus points."},
				{"GENERIC_TIP_3",       "Streaks increase with every match until you draw a new card."},
				{"GENERIC_TIP_4",       "Keep an eye on the clock. When time's up the game is over."},
				{"GENERIC_TIP_5",       "Play quickly, the faster you finish the bigger your Time Bonus."},
				{"SHARK_TIP_1", 		"Shark Cards remain until you feed them a Bait Card."},
				{"SHARK_TIP_2", 		"Those Shark Cards sure are hungry, better find those Bait Cards!"},
				{"RESHUFFLE_TIP_1",     "The game isn't over when you run out of cards. Reshuffle to keep playing!"},
				{"BOMB_TIP_1", 			"Watch out! If the Bomb explodes your game is over."},
				{"HOLD_TIP_1", 			"If you can't use a card, place it in the Hold slot for later."},
				{"WILD_TIP_1", 			"Use the Wild Card to extend a STREAK."},
				{"WILD_TIP_2", 			"Try using the Wild Card to reveal more cards."},
				{"STREAK",				"STREAK"},
				{"MAX_STREAK",			"MAX STREAK"},
				{"RED_BANNER",			"Red!!!"},
				{"BLACK_BANNER",		"Black!!!"},
				{"FLOWER_BANNER",		"Flower Blossom!!!"},
				{"VOLCANO_BANNER",		"Tiki Volcano!!!"},
				{"GOLDEN_TIKI_BANNER",	"Golden Tiki!!!"},
				{"RESHUFFLE",			"Shuffle"},
				{"BOARD_CLEARED",		"Success!"},
				{"TIMES_UP",			"Time's Up"},
				{"FINAL_SCORE",			"Results"},
				{"BOMB_EXPLODED",		"Bomb Exploded!"},
				{"TOTAL_SCORE",			"Final Score"},
				{"CARDS_SCORE",			"Card Points"},
				{"STREAKS_SCORE",		"Streak Bonus"},
				{"TIME_BONUS",			"Time Bonus"},
				{"CONTINUE_BUTTON",		"Continue"},
				{"ABORT_TITLE",			"End The Game?"},
				{"ABORT_MSG",			"Do you want to end the game? Your current score will be submitted."},
				{"ABORT_ACCEPT",		"Yes"},
				{"ABORT_CANCEL",		"No"},
				{"NO_MORE_MOVES",		"No More Moves!"},
				{"SETTINGS",			"Settings"},
				{"DETAILS",				"Details"},
				{"TIPS",				"Tips"},
				{"SOUND_FX",			"Sound FX:"},
				{"MUSIC",				"Music:"},
				{"RESHUFFLE_BANNER",	"Reshuffle!"},
				{"ABORT_TITLE_REPLAY",	"Exit this replay?"},
				{"ABORT_MSG_REPLAY",	"Do you want to exit this replay?"},
				{"SHUFFLE_DECK",		"Deck"},
				{"GENERIC_TIP_6",       "Try to reach MAX STREAK for the most points."},
				{"GENERIC_TIP_7",       "A card wiggles when you've missed a match."},
				{"GENERIC_TIP_8",       "Every match at MAX STREAK is worth 150 points!"},
				{"GENERIC_TIP_9",       "Remember, an Ace can match to a King or a 2."},
				{"RESHUFFLE_TIP_2",     "A Reshuffle takes time, so try not to miss any matches."},
				{"WILD_TIP_3", 			"Only one card left? Use the Wild Card to clear the board!"},
				{"WILD_TIP_4", 			"You only get one Wild Card, use it wisely."},
				{"WILD_TIP_5", 			"Master the Wild Card and become wildly successful!"},
				{"SHARK_TIP_3", 		"Find the Bait Card to \"abate\" the Shark Card's hunger."},
				{"BOMB_TIP_2", 			"Make sure you clear the Bomb quickly, if you wait too long... BOOM!"},
				{"BOMB_TIP_3", 			"Pro tip: Use the Wild Card to clear a Bomb."},
				{"BOMB_TIP_4", 			"Bombs can be distracting. Don't miss any matches!"},
                {"GENERIC_TIP_10",      "Bombs, Traps, and Sharks can be hidden under other cards." },
				{"TRAP_TIP_1",			"To free a trapped card, first clear the Trap."},
				{"TRAP_TIP_2",			"Don't get caught focusing on a Trap. Match other cards in the meantime."},
				{"GOLDEN_TIKI_TIP_1",	"The Golden Tiki can match any card except Shark Cards."},
				{"BLOSSOM_TIP_1",		"The Flower Blossom adds 5 cards to your deck."},
				{"VOLCANO_TIKI_TIP_1",	"The Volcano clears 5 cards from the board."},
				{"RED_TIKI_TIP_1",		"The Red Tiki clears up to 5 uncovered red cards from the board."},
				{"BLACK_TIKI_TIP_1",	"The Black Tiki clears up to 5 uncovered black cards from the board."},
				{"TUTORIAL_WELCOME",	"Welcome to Solitaire TriPeaks. The goal is to\nremove all the cards from the board."},
				{"TUTORIAL_BUTTON_HOW",	"How?"},
				{"TUTORIAL_MATCH",		"Match the card on your draw pile with any card one value higher or one lower."},
				{"TUTORIAL_REVEAL",		"Matching a card reveals any card\nbehind it."},
				{"TUTORIAL_STREAK_METER",	"Match cards without drawing to earn Streak Points."},
				{"TUTORIAL_BUTTON_GOT_IT",	"Got It"},
				{"TUTORIAL_STREAK",		"The longer the streak, the more points you earn. Keep going!"},
				{"TUTORIAL_WILD_1",     "There are no matches. Draw another card."},
				{"TUTORIAL_WILD_2",     "Still no matches. Let's use the Wild Card."},
				{"TUTORIAL_WILD_3",     "Wild Cards match any card. Try matching this one."},
				{"TUTORIAL_RESHUFFLE_1",    "No matches. Draw another card."},
				{"TUTORIAL_RESHUFFLE_2",    "Looks like you're out of cards. Reshuffle to continue."},
				{"TUTORIAL_TIME_1",     "Reshuffle is great to keep playing, but it uses up valuable time"},
                {"TUTORIAL_BUTTON_TIME",    "Time?"},
				{"TUTORIAL_TIME_2",     "You earn a Time Bonus for finishing fast!"},
				{"TUTORIAL_SCORE_1",    "Hurry, match the last cards!"},
				{"TUTORIAL_SCORE_2",    "Wow! Look at all those points."},
				{"TUTORIAL_FINAL",      "Great job! Have fun playing\nSolitaire TriPeaks."},
                {"TUTORIAL_TIME_POINTS",      "Time = More Points!"},
				{"ARENA_BACK",			"EXIT GAME"}
            };
        }
    }
}
