// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using GSN.Skill.Games.Common.Client.DebugMenu;
using UnityEngine;

namespace GSN.Skill.Games.Tripeaks
{
#if DEBUG
    public class PulldownMenu : DebugMenu
    {
        public PulldownMenu()
        {
        }

        public override void Awake()
        {
            base.Awake();

            GameObject tp = new GameObject("Tri Peaks");
			tp.AddComponent<TriPeaksDebugMenu>();
			tp.transform.parent = gameObject.transform;
			tp.SetActive(false);
            
            GameObject cardMenu = new GameObject("Tri Peaks Card Count");
			cardMenu.AddComponent<TriPeaksCardCountDebugMenu>();
			cardMenu.transform.parent = gameObject.transform;
			cardMenu.SetActive(false);
        }
    }
#endif
}

